import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Grid, mouseUp, reset } from "./js/grid";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pixel Hero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} onMouseUp={mouseUp}>
        <h1 className={styles.title}>Welcome to Pixel Hero</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div className={styles.mainDiv} id="grid">
          {Grid()}
        </div>
        <div className={styles.grid}>
          <a onClick={reset} className={styles.card}>
            <h2>RESET &rarr;</h2>
            <p>RESET DRAWING *DOESNT WORK RIGHT NOW*</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
